
opt_in_rules:
    - legacy_random
    - private_action
    - private_outlet
    - unneeded_parentheses_in_closure_argument

disabled_rules:
- force_unwrapping
- force_cast

excluded:
    - Pods
    - Generated

identifier_name:
    min_length:
    warning: 1

line_length:
    warning: 300
    error: 500
